spring:
  application:
    name: forknow
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forknow?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      #TODO : repasser ddl-auto en update
      ddl-auto: update

